import About from "@/components/About";
import Contact from "@/components/Contact";
import Feature from "@/components/Feature";
import Hero from "@/components/Hero";
import Music from "@/components/Music";
import Order from "@/components/Order";
import Review from "@/components/Review";
import Slider2 from "@/components/Slider2";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <About />
        <Feature />
        <Order />
        <Review />
        <Music />
        <Contact />
      </main>
    </>
  );
}
